config/routes.rb
Pims2::Application.routes.draw do

  resources :stakeholder_tasks

  resources :projects do
    
    
    resources :stakeholders
    resources :risks
    resources :tasks do
        collection do
            post 'savesort'
        end
    end
  
    member do
      get 'charter'
    end
  end
  
  root :to => 'projects#index'  

end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base
  belongs_to :project
  has_and_belongs_to_many :tasks
  
  scope :resources, lambda { |entity| where("is_resource = ? and project_id = ?", true, id)}
  scope :milestones, lambda { |entity| where("is_milestone = ? and project_id = ?", true, id)}
  
  
end

app/controllers/stakeholders_controller.rb
class StakeholdersController < ApplicationController
  before_filter :get_project
  before_filter :set_page_image
  
  # GET /stakeholders
  # GET /stakeholders.json
  def index
    if params[:view] == 'resources'
      @stakeholders = Project.resources(params[:project_id])
    else
      @stakeholders = Stakeholder.find_all_by_project_id(params[:project_id])
    end
    
    @stakeholder = @project.stakeholders.build # for new stakeholder

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stakeholders }
    end
  end

  # GET /stakeholders/1
  # GET /stakeholders/1.json
  def show
    @stakeholder = Stakeholder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stakeholder }
    end
  end

  # GET /stakeholders/new
  # GET /stakeholders/new.json
  def new
    @stakeholder = @project.stakeholders.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stakeholder }
    end
  end

  # GET /stakeholders/1/edit
  def edit
    @stakeholder = Stakeholder.find(params[:id])
  end

  # POST /stakeholders
  # POST /stakeholders.json
  def create
    @stakeholder = @project.stakeholders.build(params[:stakeholder])

    respond_to do |format|
      if @stakeholder.save
        format.html { redirect_to project_stakeholders_path(@project, :view => 'stakeholders'), notice: 'Stakeholder was successfully created.' }
        format.json { render json: @stakeholder, status: :created, location: @stakeholder }
      else
        format.html { render action: "new" }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stakeholders/1
  # PUT /stakeholders/1.json
  def update
    @stakeholder = Stakeholder.find(params[:id])

    respond_to do |format|
      if @stakeholder.update_attributes(params[:stakeholder])
        format.html { redirect_to project_stakeholders_path(@project, :view => 'stakeholders'), notice: 'Stakeholder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stakeholders/1
  # DELETE /stakeholders/1.json
  def destroy
    @stakeholder = Stakeholder.find(params[:id])
    @stakeholder.destroy

    respond_to do |format|
      format.html { redirect_to stakeholders_url(:project_id => @project) }
      format.json { head :no_content }
    end
  end
  
  private
  def set_page_image
    @page_image = 'stake.jpg'
  end
  
  def get_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/stakeholders/_communication_overview.html.erb
<%- model_class = Stakeholder.new.class -%>

<% if @project.stakeholders.count != 0%>

<table class="table table_no_hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:preffered_method) %></th>
    </tr>
  </thead>
  <tbody>
    <% @project.stakeholders.each do |stakeholder| %>
      <tr>
        <td><%= stakeholder.name %></td>
        <td><%= stakeholder.medium %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%else%>
  Currently no communication data
<%end%>

app/views/stakeholders/_form.html.erb
<%= form_for([@project, @stakeholder], :html => { :class => 'form-horizontal' }) do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%if params[:view] == 'communication' %>
        <%= f.text_field :name, :class => 'text_field' , :disabled=>true %>
      <%else%>
        <%= f.text_field :name, :class => 'text_field'%>
      <%end%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%if params[:view] == 'communication' %>
        <%= f.text_field :title, :class => 'text_field' , :disabled=>true%>
      <%else%>
        <%= f.text_field :title, :class => 'text_field'%>
      <%end%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :department, :class => 'control-label' %>
    <div class="controls">
      <%if params[:view] == 'communication' %>
        <%= f.text_field :department, :class => 'text_field' , :disabled=>true %>
      <%else%>
        <%= f.text_field :department, :class => 'text_field'%>
      <%end%>
    </div>
  </div>
  
  <% if params[:view] != 'communication' %>
  
  <div class="control-group">
    <%= f.label :project_role, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :project_role, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_resource, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :is_resource, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_approver, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :is_approver, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stakeholder_group, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stakeholder_group, :class => 'text_field' %>
    </div>
  </div>
  
  <%end%>
  
  <div class="control-group">
    <%= f.label :medium, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :medium, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :frequency, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :frequency, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions modal-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    
    
    <% if params[:view] == 'communication' %>
      <%= link_to 'Cancel',
                  project_stakeholders_path(@project, :view => 'communication' ), :class => 'btn' %>
    <%elsif params[:view] == 'resources'%>          
      <%= link_to 'Cancel',
                project_stakeholders_path(@project, :view => 'resources' ), :class => 'btn' %>
    <%else%>
      <%= link_to 'Cancel',
                  project_stakeholders_path(@project, :view => 'stakeholders' ), :class => 'btn' %>
    <%end%>
                
  </div>
<% end %>

app/views/stakeholders/_resources_overview.html.erb
<%- model_class = Stakeholder.new.class -%>

<% if @project.resources.count != 0%>

<table class="table table_no_hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:project_role) %></th>
    </tr>
  </thead>
  <tbody>
    <% @project.resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.project_role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%else%>
No resources
<%end%>

app/views/stakeholders/_stakeholders_overview.html.erb
<%- model_class = Stakeholder.new.class -%>

<% if @project.stakeholders.count != 0%>

<table class="table table_no_hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:project_role) %></th>
    </tr>
  </thead>
  <tbody>
    <% @project.stakeholders.each do |stakeholder| %>
      <tr>
        <td><%= stakeholder.name %></td>
        <td><%= stakeholder.project_role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%else%>
  Currently no stakeholders

<%end%>

app/views/stakeholders/edit.html.erb
<%- model_class = @stakeholder.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/stakeholders/index.html.erb
<%- model_class = Stakeholder.new.class -%>

<%= raw "<div class='modal hide in' id='new_stakeholder'>"%>
        <div layout="float: right;">
          <button type="button" class="modal-close close" data-dismiss="modal">×</button>
          <div class="modal-header">
            <h3>New Stakeholder</h3>
          </div>
          <p><%= render 'stakeholders/form', :stakeholder => @stakeholder, :project => @project%>
        </div>
     </div>
     

    <div class="well well_page_modal_header">
		  <h3>Project Stakeholders</h3>
    </div>


<br/>

<ul class="nav nav-tabs">
  <% if params[:view] == 'stakeholders'%>
    <li class="active">
  <%else%>
    <li>
  <%end%>
    	<%= link_to 'All Stakeholders' , project_stakeholders_path(@project, :view => 'stakeholders')%>
  </li>
  <% if params[:view] == 'resources'%>
    <li class="active">
  <%else%>
    <li>
  <%end%>
  <%= link_to 'Resources' , project_stakeholders_path(@project, :view => 'resources')%>
  </li>
  
  <% if params[:view] == 'communication'%>
    <li class="active">
  <%else%>
    <li>
  <%end%>
    	<%= link_to 'Communication' , project_stakeholders_path(@project, :view => 'communication')%>
  </li>
</ul>


<% @stakeholders.each do |stakeholder| %>
    <%= raw "<div class='modal hide in' id='stakeholder#{stakeholder.id}'>"%>
        <div layout="float: right;">
          <button type="button" class="modal-close close" data-dismiss="modal">×</button>
          <div class="modal-header">
            <h3>Edit</h3>
          </div>
          <%@stakeholder = stakeholder%>
          <p><%= render 'stakeholders/form', :stakeholder => @stakeholder, :project => @project%></p>
        </div>
     </div>
<%end%>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:department) %></th>
      
      <% if params[:view] == 'communication' %>
        <th><%= model_class.human_attribute_name(:preffered_method) %></th>
        <th><%= model_class.human_attribute_name(:frequency) %></th>
      <%else%>
        <th><%= model_class.human_attribute_name(:project_role) %></th>
        <th><%= model_class.human_attribute_name(:stakeholder_group) %></th>
        <th><%= model_class.human_attribute_name(:is_resource) %></th>
        <th><%= model_class.human_attribute_name(:is_approver) %></th>
      <%end%>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stakeholders.each do |stakeholder| %>
      <tr>
        <td><%= link_to stakeholder.name, project_stakeholder_path(@project,stakeholder) %></td>
        <td><%= stakeholder.title %></td>
        <td><%= stakeholder.department %></td>
         <% if params[:view] == 'communication' %>
          <td><%= stakeholder.medium %></td>
          <td><%= time_ago_in_words(Time.now - stakeholder.frequency.days) unless stakeholder.frequency.nil? %></td>     
         <%else%>
          <td><%= stakeholder.project_role %></td>
          <td><%= stakeholder.stakeholder_group %></td>
          <td><%= stakeholder.is_resource %></td>
          <td><%= stakeholder.is_approver %></td>
        <%end%>
        <td>
          <%= raw"<a class='btn btn-mini' data-toggle='modal' href='#stakeholder#{stakeholder.id}' >Edit</a>"%>
          <%= link_to t('.delete', :default => t("helpers.links.delete")),
                      project_stakeholder_path(@project,stakeholder),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' unless params[:view] == 'communication'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<div class="form-actions modal-actions">
  <%= raw"<a class='btn btn-primary' data-toggle='modal' href='#new_stakeholder' >New Stakeholder</a>"%>
</div>

app/views/stakeholders/new.html.erb
<%- model_class = @stakeholder.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/stakeholders/show.html.erb
<%- model_class = @stakeholder.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:project_id) %>:</strong><br>
  <%= @stakeholder.project_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @stakeholder.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:title) %>:</strong><br>
  <%= @stakeholder.title %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:department) %>:</strong><br>
  <%= @stakeholder.department %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:project_role) %>:</strong><br>
  <%= @stakeholder.project_role %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:is_resource) %>:</strong><br>
  <%= @stakeholder.is_resource %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:is_approver) %>:</strong><br>
  <%= @stakeholder.is_approver %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:stakeholder_group) %>:</strong><br>
  <%= @stakeholder.stakeholder_group %>
</p>

<div class="form-actions modal-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              project_stakeholders_path(@stakeholder.project_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_stakeholder_path(@stakeholder.project_id, @stakeholder), :class => 'btn' %>
  <%= link_to t('.delete', :default => t("helpers.links.delete")),
              project_stakeholder_path(@stakeholder.project_id, @stakeholder),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>