config/routes.rb
Pims2::Application.routes.draw do

  resources :stakeholder_tasks

  resources :projects do
    
    
    resources :stakeholders
    resources :risks
    resources :tasks do
        collection do
            post 'savesort'
        end
    end
  
    member do
      get 'charter'
    end
  end
  
  root :to => 'projects#index'  

end

app/models/risk.rb
class Risk < ActiveRecord::Base
    belongs_to :project
    
  def rating
    if likelihood.nil? or consequence.nil?
      0
    else
      likelihood * consequence  
    end
  end
end

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  before_filter :get_project
  before_filter :set_page_image
  # GET /risks
  # GET /risks.json
  def index
    @risks = Risk.find_all_by_project_id(params[:project_id])
    @risk = @project.risks.build # for new risk

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @risks }
    end
  end

  # GET /risks/1
  # GET /risks/1.json
  def show
    @risk = Risk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @risk }
    end
  end

  # GET /risks/new
  # GET /risks/new.json
  def new
    @risk = @project.risks.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @risk }
    end
  end

  # GET /risks/1/edit
  def edit
    @risk = Risk.find(params[:id])
  end

  # POST /risks_url
  # POST /risks.json
  def create
    @risk = @project.risks.build(params[:risk])

    respond_to do |format|
      if @risk.save
        format.html { redirect_to project_risks_path(@project), notice: 'Risk was successfully created.' }
        format.json { render json: @risk, status: :created, location: @risk }
      else
        format.html { render action: "new" }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /risks/1
  # PUT /risks/1.json
  def update
    @risk = Risk.find(params[:id])

    respond_to do |format|
      if @risk.update_attributes(params[:risk])
        format.html { redirect_to project_risks_path(@project), notice: 'Risk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risks/1
  # DELETE /risks/1.json
  def destroy
    @risk = Risk.find(params[:id])
    @risk.destroy

    respond_to do |format|
      format.html { redirect_to risks_url(:project_id => @project) }
      format.json { head :no_content }
    end
  end
  
  private
  def set_page_image
    @page_image = 'questionmark.jpg'
  end
  
  def get_project
    @project = Project.find(params[:project_id])
  end
  
end

app/helpers/risks_helper.rb
module RisksHelper
end

app/views/risks/_form.html.erb
<%= form_for([@project, @risk], :html => { :class => 'form-horizontal' } ) do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cost, :class => 'control-label' %>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :cost, :class => 'text_field' %>
        <span class="add-on">$</span>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :delay, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :delay, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :likelihood, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :likelihood, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :consequence, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :consequence, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mitigation, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :mitigation, :class => 'text_area' %>
    </div>
  </div>


  <div class="form-actions modal-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel',
                project_risks_path(@project), :class => 'btn' %>
  </div>
<% end %>

app/views/risks/_risk_overview.html.erb
<%- model_class = Risk.new.class -%>

<% if @project.risks.count != 0%>

<table class="table table_no_hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
    </tr>
  </thead>
  <tbody>
    <% @project.risks.each do |risk| %>
      <tr>
        <td><%= risk.name %></td>
        <td><%= risk.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%else%>
  Currently no risks
<%end%>

app/views/risks/edit.html.erb
<%- model_class = @risk.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/risks/index.html.erb
<%- model_class = Risk.new.class -%>

<%= raw "<div class='modal hide in' id='new_risk'>"%>
        <div layout="float: right;">
          <button type="button" class="modal-close close" data-dismiss="modal">×</button>
          <div class="modal-header">
            <h3>New Risk</h3>
          </div>
          <p><%= render 'risks/form', :risk => @risk, :project => @project%>
        </div>
     </div>
     


<div class="well well_page_modal_header">
		  <h3>Risks</h3>
</div>

<% @risks.each do |risk| %>
    <%= raw "<div class='modal hide in' id='risk#{risk.id}'>"%>
        <div layout="float: right;">
          <button type="button" class="modal-close close" data-dismiss="modal">×</button>
          <div class="modal-header">
            <h3>Edit Risk</h3>
          </div>
          <%@risk = risk%>
          <p><%= render 'risks/form', :risk => @risk, :project => @project%></p>
        </div>
     </div>
<%end%>
     
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:cost) %></th>
      <th><%= model_class.human_attribute_name(:delay) %></th>
      <th><%= model_class.human_attribute_name(:likelihood) %></th>
      <th><%= model_class.human_attribute_name(:consequence) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:mitigation) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @risks.each do |risk| %>
      <tr>
        <td><%= link_to risk.id, project_risk_path(@project,risk) %></td>
        <td><%= link_to risk.name, project_risk_path(@project, risk) %></td>
        <td><%= risk.description %></td>
        <td><%= number_to_currency(risk.cost) unless risk.cost.nil? %></td>
        <td><%= time_ago_in_words(Time.now - risk.delay.days) unless risk.delay.nil? %></td>
        <td><%= risk.likelihood %></td>
        <td><%= risk.consequence %></td>
        <td><%= risk.rating %></td>
        <td><%= risk.mitigation %></td>
        <td>
          <%= raw"<a class='btn btn-mini' data-toggle='modal' href='#risk#{risk.id}' >Edit</a>"%>
          <%= link_to t('.delete', :default => t("helpers.links.delete")),
                      project_risk_path(@project,risk),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions modal-actions">
  <%= raw"<a class='btn btn-primary' data-toggle='modal' href='#new_risk' >Add Risk</a>"%>
</div>

app/views/risks/new.html.erb
<%- model_class = @risk.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/risks/show.html.erb
<%- model_class = @risk.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @risk.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:description) %>:</strong><br>
  <%= @risk.description %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:cost) %>:</strong><br>
  <%= @risk.cost %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:delay) %>:</strong><br>
  <%= @risk.delay %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:likelihood) %>:</strong><br>
  <%= @risk.likelihood %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:consequence) %>:</strong><br>
  <%= @risk.consequence %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:mitigation) %>:</strong><br>
  <%= @risk.mitigation %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:project_id) %>:</strong><br>
  <%= @risk.project_id %>
</p>

<div class="form-actions modal-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              project_risks_path(@risk.project_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_risk_path(@risk.project_id,@risk), :class => 'btn' %>
  <%= link_to t('.delete', :default => t("helpers.links.delete")),
              project_risk_path(@risk.project_id,@risk),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>