config/routes.rb
Pims2::Application.routes.draw do

  resources :stakeholder_tasks

  resources :projects do
    
    
    resources :stakeholders
    resources :risks
    resources :tasks do
        collection do
            post 'savesort'
        end
    end
  
    member do
      get 'charter'
    end
  end
  
  root :to => 'projects#index'  

end

app/controllers/nav_controller.rb
class NavController < ApplicationController
 
  def projects
    @projects = Project.order(:title)

    respond_to do |format|
      format.html # projects.html.erb
      format.json { render json: @projects }
    end
  end

  def canvas
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # canvas.html.erb
      format.json { render json: @project }
    end
  end

  def charter
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks
    respond_to do |format|
      format.html # charter.html.erb
      format.json { render json: @project }
    end
  end

  def details
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # details.html.erb
      format.json { render json: @project }
    end
  end

  def scope
    @project = Project.find(params[:project_id])
    @task_row_number = 0

    respond_to do |format|
      format.html # scope.html.erb
      format.json { render json: @project }
    end
  end

  def cost
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # cost.html.erb
      format.json { render json: @project }
    end
  end

  def schedule
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # schedule.html.erb
      format.json { render json: @project }
    end
  end

  def communications
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # communications.html.erb
      format.json { render json: @project }
    end
  end

  def risk
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # risk.html.erb
      format.json { render json: @project }
    end
  end

  def procurement
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # procurement.html.erb
      format.json { render json: @project }
    end
  end

  def quality
  end

  def resources
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # resources.html.erb
      format.json { render json: @project }
    end
  end
  
  def delete_project
    @project = Project.find(params[:project_id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to nav_projects_path }
      format.json { head :no_content }
    end
  end
  
  def new_project
    @project = Project.new(title: "New Project")
    @project.save
    @task = Task.new(name: "Project Header Task", project_id: @project.id, level: 0, parent_task_id: -1)
    @task.save

    respond_to do |format|
      format.html { redirect_to nav_details_path(project_id: @project) }
 #      format.html { redirect_to nav_projects_path }
      format.json { render json: @project }
    end
  end
  
  def update_project
    @project = Project.find(params[:project_id])
    @current_page = params[:current_page]
    respond_to do |format|
      if @project.update_attributes(params[:project])
        if @current_page == 'details'
          format.html { redirect_to nav_details_path(project_id: @project) }    #  format.html { redirect_to nav_details_path(project_id: @project), notice: 'Project was successfully updated.' }
        elsif @current_page == 'scope'
          format.html { redirect_to nav_scope_path(project_id: @project) }
        elsif @current_page == 'cost'
          format.html { redirect_to nav_cost_path(project_id: @project) }
        elsif @current_page == 'procurement'
          format.html { redirect_to nav_procurement_path(project_id: @project) }
        elsif @current_page == 'schedule'
          format.html { redirect_to nav_schedule_path(project_id: @project) }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_task
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
    @sibling_tasks = Project.find(params[:project_id]).tasks.where("parent_task_id = ?", @task.parent_task_id)

    @child_tasks = Task.where("parent_task_id = ?", params[:task_id])
    @child_tasks.each do |child|
 #     delete_task(:project_id => @project, :task_id => child)     # cannot pass arguments again - reading from same hash. need to break out into helper method!!!!!! need to destroy or reassign children.
    end

    @task.destroy

    respond_to do |format|
      format.html { redirect_to nav_scope_path(project_id: @project) }
      format.json { head :no_content }
    end
  end
  
  def new_task
    @project = Project.find(params[:project_id])
    @header_task = Task.where("project_id = ? AND level = ?",@project.id, 0).first

    @first_level_tasks = Task.where("parent_task_id = ?",@header_task.id)
    @index = 0
    @first_level_tasks.each do |task|
      if task.level > @index
        @index = task.level
      end
    end
    @index += 1

    @task = Task.new(name: "New Task", project_id: @project.id, level: @index, parent_task_id: @header_task.id)
    @task.save

    respond_to do |format|
      format.html { redirect_to nav_scope_path(project_id: @project) }
      format.json { render json: @task }
    end
  end

  def update_tasks
    @project = Project.find(params[:project_id])
    respond_to do |format|
      if @project.update_attributes(params[:project])
 #       @project.tasks.each do |task|
 #         if task.level == 0
 #           set_task_level(task_id: task.id, level: 0)
 #         end
 #       end
        format.html { redirect_to nav_scope_path(project_id: @project) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_stakeholder
    @project = Project.find(params[:project_id])
    @current_page = params[:current_page]
    @stakeholder = Stakeholder.find(params[:stakeholder_id])
    @stakeholder.destroy

    respond_to do |format|
        if @current_page == 'communications'
          format.html { redirect_to nav_communications_path(project_id: @project) }    
        elsif @current_page == 'resources'
          format.html { redirect_to nav_resources_path(project_id: @project) }
        end
      format.json { head :no_content }
    end
  end
  
  def new_stakeholder
    @project = Project.find(params[:project_id])
    @current_page = params[:current_page]
    @stakeholder = Stakeholder.new(name: "New Stakeholder", project_id: @project.id)
    @stakeholder.save

    respond_to do |format|
        if @current_page == 'communications'
          format.html { redirect_to nav_communications_path(project_id: @project) }    
        elsif @current_page == 'resources'
          format.html { redirect_to nav_resources_path(project_id: @project) }
        end
      format.json { render json: @stakeholder }
    end
  end

  def update_stakeholders
    @project = Project.find(params[:project_id])
    @current_page = params[:current_page]
    respond_to do |format|
      if @project.update_attributes(params[:project])
        if @current_page == 'communications'
          format.html { redirect_to nav_communications_path(project_id: @project) }    
        elsif @current_page == 'resources'
          format.html { redirect_to nav_resources_path(project_id: @project) }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_risk
    @project = Project.find(params[:project_id])
    @risk = Risk.find(params[:risk_id])
    @risk.destroy

    respond_to do |format|
      format.html { redirect_to nav_risk_path(project_id: @project) }
      format.json { head :no_content }
    end
  end

  def new_risk
    @project = Project.find(params[:project_id])
    @risk = Risk.new(name: "New Risk", project_id: @project.id)
    @risk.save

    respond_to do |format|
      format.html { redirect_to nav_risk_path(project_id: @project) }
      format.json { render json: @stakeholder }
    end
  end

  def update_risks
    @project = Project.find(params[:project_id])
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to nav_risk_path(project_id: @project) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/nav_helper.rb
module NavHelper
end

app/views/nav/_render_child_tasks.html.erb

<%= tasks_to_render = @project.tasks.where("parent_task_id = ?", parent_task_id); nil %>
<%= count = 1; nil %>
<%= while count <= tasks_to_render.size do %>
  <%= task = tasks_to_render.where("level = ?", count); nil %>
  <%= @task_row_number += 1; nil %>
  <%= project_form.fields_for :tasks, task, :child_index => @task_row_number do |task_fields| %>     <!-- may be better way, but using each_with_index spat excess to screen.  -->
    <%= render :partial => "task", :locals => { :index_prefix => index_prefix, :task_fields => task_fields } %>
  <% end %>
   <%= if index_prefix == ""
        child_index_prefix = count.to_s() + "."
      else
        child_index_prefix = index_prefix + count.to_s() + "."
      end; nil %>
  <%= render :partial => "render_child_tasks", :locals => { :project_form => project_form, :parent_task_id => tasks_to_render.where("level = ?", count).first, :index_prefix => child_index_prefix } %>
  <%= count += 1; nil %>
<% end %>




app/views/nav/_task.html.erb
<tr>
 <td><%= task_fields.object.id %></td>
 <td>
   <%= index_prefix + task_fields.object.level.to_s() %>
   <%= task_fields.hidden_field :task_index, :value => index_prefix + task_fields.object.level.to_s() %>
 </td>
 <td>
   <div class="field">
     <%= index_prefix.gsub(%r([1234567890]),'&nbsp&nbsp&nbsp').gsub(%r([.]),'').html_safe + " " %><%= task_fields.text_field :name, size: 20 %>
  </div>                                        
 </td>
 <td>
   <div class="field">
    <%= task_fields.text_area :description, cols: 35, rows: 1 %>
   </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.date_select :start_date %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.date_select :end_date %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.check_box :is_milestone %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.number_field :parent_task_id, size: 3 %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.number_field :level, size: 3 %>
  </div>
 </td>
 <td><%= link_to 'Delete', nav_delete_task_path(project_id: @project, task_id: task_fields.object), confirm: 'Are you sure you want to delete this task?' %></td>
</tr>

app/views/nav/_task_row.html.erb
<tr>
 <td><%= task_fields.object.id %></td>
 <td><% index_prefix  %><%= task_fields.object.level.to_s() %></td>
 <td>
   <div class="field">
     <%= task_fields.text_field :name, size: 20 %>
  </div>
 </td>
 <td>
   <div class="field">
    <%= task_fields.text_area :description, cols: 35, rows: 1 %>
   </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.date_select :start_date %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.date_select :end_date %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.check_box :is_milestone %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.number_field :parent_task_id, size: 3 %>
  </div>
 </td>
 <td>
  <div class="field">
    <%= task_fields.number_field :level, size: 3 %>
  </div>
 </td>
 <td><%= link_to 'Delete', nav_delete_task_path(project_id: @project, task_id: task_fields.object), confirm: 'Are you sure you want to delete this task?' %></td>
</tr>

app/views/nav/canvas.html.erb
<!--
<h1>Nav#canvas</h1>
<p>Find me in app/views/nav/canvas.html.erb</p>
-->
<h1>Project Canvas: <%= @project.title %></h1>

<p id="notice"><%= notice %></p>

<p>
  <!-- <h2>Project Details</h2> -->
  <h2><%= link_to 'Project Details ', nav_details_path(project_id: @project) %></h2>
</p>
<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Responsible group:</b>
  <%= @project.responsible_group %>
</p>

<p>
  <b>Cost centre:</b>
  <%= @project.cost_centre %>
</p>

<p>
<!--  <h2>Scope</h2> -->
  <h2><%= link_to 'Scope', nav_scope_path(project_id: @project) %></h2>
</p>
<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <h2><%= link_to 'Cost', nav_cost_path(project_id: @project) %></h2>
</p>
<p>
  <b>Budget:</b>
  <%= @project.budget %>
</p>

<p>
  <b>Contingency:</b>
  <%= @project.contingency %>
</p>

<p>
  <b>Budget accuracy:</b>
  <%= @project.budget_accuracy %>
</p>

<p>
  <h2><%= link_to 'Schedule', nav_schedule_path(project_id: @project) %></h2>
</p>
<p>
  <b>Start date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @project.end_date %>
</p>

<p>
  <!-- <h2>Communications</h2> -->
   <h2><%= link_to 'Communications', nav_communications_path(project_id: @project) %></h2>
</p>
<h3>Stakeholders</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Project role</th>
  </tr>

<% @project.stakeholders.where(:is_resource => false).each do |stakeholder| %>
  <tr>
    <td><%= stakeholder.name %></td>
    <td><%= stakeholder.project_role %></td>
  </tr>
<% end %>
</table>



<p>
  <h2><%= link_to 'Risk', nav_risk_path(project_id: @project) %></h2>
</p>

<h3>Project Risks</h3>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

<% @project.risks.order("name").each do |risk| %>
  <tr>
    <td><%= risk.name %></td>
    <td><%= risk.description %></td>
  </tr>
<% end %>
</table>


<p>
  <!-- <h2>Procurement</h2>    -->
  <h2><%= link_to 'Procurement', nav_procurement_path(project_id: @project) %></h2>
</p>
<p>
  <b>Procurement strategy:</b>
  <%= @project.procurement_strategy %>
</p>

<p>
  <h2>Quality</h2>
</p>

<p>
  <h2><%= link_to 'Resources', nav_resources_path(project_id: @project) %></h2>
</p>
<h3>Project Team</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Project role</th>
  </tr>

<% @project.stakeholders.where(:is_resource => true).each do |stakeholder| %>
  <tr>
    <td><%= stakeholder.name %></td>
    <td><%= stakeholder.project_role %></td>
  </tr>
<% end %>
</table>
<p>
<%= link_to 'Generate Project Charter', nav_charter_path(project_id: @project) %>
</p>

<p>
<%= link_to 'Back to Projects', nav_projects_path %>
</p>

<!--
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
-->

app/views/nav/cost.html.erb
<!--
<h1>Nav#cost</h1>
<p>Find me in app/views/nav/cost.html.erb</p>
-->

<h1>Cost: <%= @project.title %></h1>

<p id="notice"><%= notice %></p>

<%= form_for(@project, url: nav_update_project_path(project_id: @project, current_page: 'cost')) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost_centre %><br />
    <%= f.text_field :cost_centre %>
  </div>
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :contingency %><br />
    <%= f.text_field :contingency %>
  </div>
  <div class="field">
    <%= f.label :budget_accuracy %><br />
    <%= f.text_field :budget_accuracy %>
  </div>
  <div class="actions">
    <%= f.submit "Save Changes"%>
  </div>
<% end %>
<div>
<%= button_to 'Discard Changes', nav_cost_path(project_id: @project), confirm: 'Are you sure you want to discard changes?'%>
</div>
<div>
<p><%= link_to 'Back to Project Canvas', nav_canvas_path(project_id: @project) %></p>
</div>
<!--
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
-->

app/views/nav/details.html.erb
<!--
<h1>Nav#details</h1>
<p>Find me in app/views/nav/details.html.erb</p>
-->
<h1>Project Details: <%= @project.title %></h1>

<p id="notice"><%= notice %></p>

<%= form_for(@project, url: nav_update_project_path(project_id: @project, current_page: 'details')) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
<!--
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
-->
  <div class="field">
    <%= f.label :responsible_group %><br />
    <%= f.text_field :responsible_group %>
  </div>
  <div class="field">
    <%= f.label :cost_centre %><br />
    <%= f.text_field :cost_centre %>
  </div>
    <div class="field">
    <%= f.label :purpose %><br />
    <%= f.text_area :purpose, cols: 100, rows: 6%>
  </div>
<!--
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :contingency %><br />
    <%= f.text_field :contingency %>
  </div>
  <div class="field">
    <%= f.label :budget_accuracy %><br />
    <%= f.text_field :budget_accuracy %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :procurement_strategy %><br />
    <%= f.text_area :procurement_strategy %>
  </div>
-->
  <div class="actions">
    <%= f.submit "Save Changes"%>
  </div>
<% end %>
<div>
<%= button_to 'Discard Changes', nav_details_path(project_id: @project), confirm: 'Are you sure you want to discard changes?'%>
</div>
<div>
<p><%= link_to 'Back to Project Canvas', nav_canvas_path(project_id: @project) %></p>
</div>
<!--
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
-->

app/views/nav/procurement.html.erb
<!--
<h1>Nav#procurement</h1>
<p>Find me in app/views/nav/procurement.html.erb</p>
-->

<h1>Procurement: <%= @project.title %></h1>

<p id="notice"><%= notice %></p>

<%= form_for(@project, url: nav_update_project_path(project_id: @project, current_page: 'procurement')) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :procurement_strategy %><br />
    <%= f.text_area :procurement_strategy, cols: 100, rows: 6 %>
  </div>

  <div class="actions">
    <%= f.submit "Save Changes"%>
  </div>
<% end %>
<div>
<%= button_to 'Discard Changes', nav_procurement_path(project_id: @project), confirm: 'Are you sure you want to discard changes?'%>
</div>
<div>
<p><%= link_to 'Back to Project Canvas', nav_canvas_path(project_id: @project) %></p>
</div>
<!--
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
-->

app/views/nav/projects.html.erb
<!--
<h1>Nav#projects</h1>
<p>Find me in app/views/nav/projects.html.erb</p>
-->
<h1>Projects</h1>

<table>
  <tr> 

    <th>ID</th>

    <th>Title</th>
    <th>Description</th>
<!--
    <th>Responsible group</th>
    <th>Cost centre</th>
    <th>Budget</th>
    <th>Contingency</th>
    <th>Budget accuracy</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Procurement strategy</th>
    <th></th>
    <th></th>
    <th></th>
-->
  </tr>

<% @projects.each do |project| %>
  <tr>
<!--
    <td><%= link_to project.title, project %></td>
-->
    <td><%= project.id %></td>

    <td><%= link_to project.title, nav_canvas_path(project_id: project) %></td>     
    <td><%= project.description %></td>
<!--
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= project.responsible_group %></td>
    <td><%= project.cost_centre %></td>
    <td><%= project.budget %></td>
    <td><%= project.contingency %></td>
    <td><%= project.budget_accuracy %></td>
    <td><%= project.start_date %></td>
    <td><%= project.end_date %></td>
    <td><%= project.procurement_strategy %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'Delete', project, confirm: 'Are you sure?', method: :delete %></td>
-->
    <td><%= link_to 'Delete', nav_delete_project_path(project_id: project), confirm: 'Are you sure you want to delete this project?' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create New Project', nav_new_project_path %>

app/views/nav/schedule.html.erb
<!-- <h1>Nav#schedule</h1>
<p>Find me in app/views/nav/schedule.html.erb</p>
-->

<h1>Schedule: <%= @project.title %></h1>

<p id="notice"><%= notice %></p>

<%= form_for(@project, url: nav_update_project_path(project_id: @project, current_page: 'schedule')) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit "Save Changes"%>
  </div>
<% end %>
<div>
<%= button_to 'Discard Changes', nav_schedule_path(project_id: @project), confirm: 'Are you sure you want to discard changes?'%>
</div>
<div>
<p><%= link_to 'Back to Project Canvas', nav_canvas_path(project_id: @project) %></p>
</div>
<!--
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
-->

app/views/nav/scope.html.erb
<!--
<h1>Nav#scope</h1>
<p>Find me in app/views/nav/scope.html.erb</p>
-->
<h1>Project Scope: <%= @project.title %></h1>

<p id="notice"><%= notice %></p>

<%= form_for(@project, url: nav_update_project_path(project_id: @project, current_page: 'scope')) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
-->
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, cols: 100, rows: 6%>
  </div>
<!--
  <div class="field">
    <%= f.label :responsible_group %><br />
    <%= f.text_field :responsible_group %>
  </div>
  <div class="field">
    <%= f.label :cost_centre %><br />
    <%= f.text_field :cost_centre %>
  </div>
  <div class="field">
    <%= f.label :budget %><br />
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :contingency %><br />
    <%= f.text_field :contingency %>
  </div>
  <div class="field">
    <%= f.label :budget_accuracy %><br />
    <%= f.text_field :budget_accuracy %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :procurement_strategy %><br />
    <%= f.text_area :procurement_strategy %>
  </div>
-->
  <div class="actions">
    <%= f.submit "Save Description"%>
  </div>
<% end %>


<!-- START TASKS 2 -->

<h3>Work Breakdown Structure</h3>

<% @project.tasks.each do |task| %>         <!-- ENSURE THIS CODE CHECKS ERRORS SENT THROUGH FROM BOTH PROJECT AND TASKS -->
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<table>

  <tr>
    <th>ID</th>
<!--
    <th>Project</th>
-->
    <th>Index</th>
    <th>Name</th>
    <th>Description</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Is Milestone</th>
    <th>Parent task</th>
    <th>Level</th>
<!--
    <th>Procurement method</th>
    <th>Budget</th>
    <th></th>
-->
    <th></th>
    <th></th>
  </tr>

  <%= form_for(@project, url: nav_update_tasks_path(project_id: @project)) do |project_form| %>
  
  <%= @task_row_number = 0; nil %>

  <%= project_form.fields_for :tasks, @project.tasks.where("parent_task_id = ?", -1).first, :child_index => @task_row_number do |task_fields| %>     <!-- may be better way, but using each_with_index spat excess to screen.  -->
  <%= index_prefix = "" %>
    <%= render :partial => "task", :locals => { :index_prefix => index_prefix, :task_fields => task_fields } %>
  <% end %>



    <%= render :partial => "render_child_tasks", :locals => { :project_form => project_form, :parent_task_id => @project.tasks.where("parent_task_id = ?", -1).first, :index_prefix => "" } %>

</table>

<p><%= link_to 'Create New Task', nav_new_task_path(project_id: @project) %></p>
<div class="actions">
  <%= project_form.submit "Save Tasks" %>
</div>
  <% end %>
<!-- END TASK2 -->

<p><%= button_to 'Discard Changes', nav_scope_path(project_id: @project), confirm: 'Are you sure you want to discard changes?'%></p>

<div>
<p><%= link_to 'Back to Project Canvas', nav_canvas_path(project_id: @project) %></p>
</div>
<!--
<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
-->