config/routes.rb
Pims2::Application.routes.draw do

  resources :stakeholder_tasks

  resources :projects do
    
    
    resources :stakeholders
    resources :risks
    resources :tasks do
        collection do
            post 'savesort'
        end
    end
  
    member do
      get 'charter'
    end
  end
  
  root :to => 'projects#index'  

end

app/views/layouts/_dashboard.erb
<%- model_class = @project.class -%>

<div class="dashboard_header well">
			<%= @project.title%>
	</div>
	
<div class="well dashboard_background" style="padding: 8px 0;">
						<ul class="nav nav-list">
							<li>
								<%= link_to raw("<i class='icon-white icon-home'></i> Project Canvas") , project_path(@project, :view => 'overview')%>
							</li>
							<li>
								<%= link_to raw("<i class='icon-file'></i> Project Details") , project_path(@project, :view => 'details')%>
							</li>
							<li>
							  <%= link_to raw("<i class='icon-resize-full'></i> Scope") , project_path(@project, :view => 'scope')%>
							</li>
							<li>
								<%= link_to raw("<i class='icon-check'></i> Milestones") , project_tasks_path(@project)%>							
							</li>
							<li>
								 <%= link_to raw("<i class='icon-dollar'></i> Cost") , project_path(@project, :view => 'cost')%>
							</li>
							<li>
								<%= link_to raw("<i class='icon-time'></i> Schedule") , project_path(@project, :view => 'schedule')%>
							</li>
							<li>
								<%= link_to raw("<i class='icon-user'></i> Stakeholders") , project_stakeholders_path(@project, :view => 'stakeholders')%>
							</li>
							<li>
								<%= link_to raw("<i class='icon-fire'></i> Risks") , project_risks_path(@project)%>
							</li>
							<li>
					
								<%= link_to raw("<i class='icon-shopping-cart'></i> Procurement") , project_path(@project, :view => 'procurement')%>
							</li>
							<li>
					
								<%= link_to raw("<i class='icon-map-marker'></i> Resources") , project_stakeholders_path(@project, :view => 'resources')%>
							</li>
							
							<li>
								<%= link_to raw("<i class='icon-envelope'></i> Communication") , project_stakeholders_path(@project, :view => 'communication')%>
							</li>

						</ul>
					</div>

app/views/layouts/_footer.erb
  <script type="text/javascript" charset="utf-8">
  
$('.datepicker').datepicker({
    format: 'dd/mm/yyyy'
});

//Moved to footer file, so the box sizes can be calculated after the page is rendered

    //<![CDATA[
$(function(){
  $('.well_details_table').css({
  'height': $('.overview_well_table').height()
  });
  $('.well_details').css({
  'height': $('.overview_well_procurement').height()
  });
  $('.well_details_details').css({
  'height': $('.overview_well_details2').height()
  });
});//]]> 
</script>

app/views/layouts/_header.erb
<div class="navbar navbar-fixed-top ">
  <div class="navbar-inner">
    <div class="container navigation-offset-left">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "PIMS" , projects_path , :class=>'brand'%>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Projects List" , projects_path%></li>
        </ul>
      </div>
    </div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "datepicker" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
     <%= javascript_include_tag "jquery" %>
     <%= javascript_include_tag "jquery.min" %>
     <%= javascript_include_tag "jquery-ui" %>
     <%= javascript_include_tag "bootstrap-datepicker" %>

     <%= javascript_include_tag 'nestedsortables.min' %>

  <script type="text/javascript" charset="utf-8">
    $(function() {
      $("#sortable").nestedSortable({
        listType: 'ul',
        items: 'li',
        placeholder: "highlight",
        forcePlaceholderSize: true,
        handle: 'div',
        helper: 'clone',
        opacity: .6,
        revert: 250,
        tabSize: 45,
        tolerance: 'pointer',
        toleranceElement: '> div',
        connectWith: '#sortable',
              
      update: function () {
        list = $(this).nestedSortable('toHierarchy', {startDepthCount: 0});
        c = {set : JSON.stringify($('#sortable').nestedSortable('toHierarchy', {startDepthCount: 0}))};
        $.post(
            'tasks/savesort',
            c,
            function(data){
            
              // Automatic refreshing page - there are other approaches, but leave this as a demo for now
              window.location.href= "tasks";
            },
            "html"
        );
    }
      });
      $("#sortable").disableSelection(); // make links not clickable
      $('#serialize').click(function (){
      
        // START CODE FOR REFRESHING TASKS ON PUSH OF BUTTON - left for just in case needed later - just call url #serialize
        
        var c = {set : JSON.stringify($('#sortable').nestedSortable('toHierarchy', {startDepthCount: 0}))};
        var post_link = "tasks/savesort";
        $.post(post_link, c, $('#output').html('<p id="flash_notice">Saved Successfully</p>'));
        
        var form = document.createElement("form");
        form.setAttribute("method", "method");
        form.setAttribute("action", "tasks");
        var hiddenField = document.createElement("input");
        hiddenField.setAttribute("type", "hidden"); // 'hidden' is the less annoying html data control
        hiddenField.setAttribute("name", "json_data");
        hiddenField.setAttribute("value", c);
        form.appendChild(hiddenField); // append the newly created control to the form
        
        document.body.appendChild(form); // inject the form object into the body section
        form.submit();
    
        eturn false;
      });
    });
    
    

  </script>

  
  <title><%= if @project.nil? or @project.title.nil? then "PIMS" else @project.title + " - PIMS" end%></title>   
  
</head>
<body>

<div class="container-fluid">
<%= render :partial => 'layouts/header' %>  
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>

    <div class="row">
        <div class="span2 span-dashboard">
          <%if !@project.nil? && !@project.new_record?%>
			      <%= render :partial => 'layouts/dashboard' %>  
		
			    <%else%>
			       <%= " "%>
			    <%end%>
			
		    </div>
		    <div class="span1">
		      &nbsp;
		    </div>
		    <div class="span8">
			    <%= yield %>
		    </div>
		
	</div>
</div>

<%= render :partial => 'layouts/footer' %>  

</body>
</html>

app/views/layouts/charter.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Charter</title>
   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  
  
</head>
<body>




<div class="container navigation-offset-left">
    <div class="row">
          <%if !@project.nil? && !@project.new_record?%>

		<div class="span8">
			<%= yield %>
		</div>
          <%end%>
		
	</div>
</div>
   

</body>
</html>